{% set name = "calver" %}
{% set version = "2025.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/calver-{{ version }}.tar.gz
  sha256: 460702737d620f5c3d4175450485180a1b7f7a422c5db0e6af3e655c7395ec7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.1
  run:
    - python >={{ python_min }}

test:
  imports:
    - calver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/di/calver
  summary: Setuptools extension for CalVer package versions
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
